version: '2'

services:
  flask:
    restart: always
    build: .
    expose:
      - "${PORT}"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=server:${PORT}"
      - "traefik.frontend.rule=Host:${FRONTEND}"
    networks:
    - "reverseproxy"
    command: /usr/local/bin/gunicorn -w 2 -b :${PORT} wsgi:app

networks:
  reverseproxy:
    external:
      name: ${NETWORK}